"""Adding Tables

Revision ID: 342acd7dc24d
Revises: ad514e69bf60
Create Date: 2023-10-08 12:29:36.176930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '342acd7dc24d'
down_revision = 'ad514e69bf60'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colores_id'), 'colores', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_colores_id'), table_name='colores')
    op.drop_table('colores')
    # ### end Alembic commands ###
