"""Adding Tables

Revision ID: 54a1e1632197
Revises: 342acd7dc24d
Create Date: 2023-10-08 12:59:53.521072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a1e1632197'
down_revision = '342acd7dc24d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_text', sa.Integer(), nullable=True, comment='Este campo hace alucion a los campos de colorModels'),
    sa.Column('main', sa.String(length=50), nullable=True),
    sa.Column('date_50', sa.String(length=50), nullable=True),
    sa.Column('date_100', sa.String(length=50), nullable=True),
    sa.Column('date_200', sa.String(length=50), nullable=True),
    sa.Column('date_300', sa.String(length=50), nullable=True),
    sa.Column('date_400', sa.String(length=50), nullable=True),
    sa.Column('date_500', sa.String(length=50), nullable=True),
    sa.Column('date_600', sa.String(length=50), nullable=True),
    sa.Column('date_700', sa.String(length=50), nullable=True),
    sa.Column('date_800', sa.String(length=50), nullable=True),
    sa.Column('date_900', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_color_id'), 'tipo_color', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipo_color_id'), table_name='tipo_color')
    op.drop_table('tipo_color')
    # ### end Alembic commands ###
