"""Adding Tables

Revision ID: ac0e8725fa7e
Revises: 54a1e1632197
Create Date: 2023-10-08 13:37:49.099251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac0e8725fa7e'
down_revision = '54a1e1632197'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tipo_color', sa.Column('default', sa.String(length=50), nullable=True))
    op.add_column('tipo_color', sa.Column('paper', sa.String(length=50), nullable=True))
    op.add_column('tipo_color', sa.Column('primary', sa.String(length=50), nullable=True))
    op.add_column('tipo_color', sa.Column('secondary', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tipo_color', 'secondary')
    op.drop_column('tipo_color', 'primary')
    op.drop_column('tipo_color', 'paper')
    op.drop_column('tipo_color', 'default')
    # ### end Alembic commands ###
