"""Adding Tables

Revision ID: ad514e69bf60
Revises: 
Create Date: 2023-10-08 11:05:13.930152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad514e69bf60'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('usuario', sa.String(length=255), nullable=True),
    sa.Column('pass', sa.String(length=255), nullable=True),
    sa.Column('id_nivel', sa.String(length=255), nullable=True),
    sa.Column('codempresa', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('fechaacceso', sa.DateTime(), nullable=True),
    sa.Column('fechapass', sa.DateTime(), nullable=True),
    sa.Column('borrado', sa.Integer(), nullable=True),
    sa.Column('pendiente', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    # ### end Alembic commands ###
