"""Adding Tables

Revision ID: cea25b263f06
Revises: 
Create Date: 2023-10-18 16:31:45.896829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea25b263f06'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('state', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colores_id'), 'colores', ['id'], unique=False)
    op.create_table('tipo_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_text', sa.Integer(), nullable=True, comment='Este campo hace alucion a los campos de colorModels'),
    sa.Column('main', sa.String(length=50), nullable=True),
    sa.Column('50', sa.String(length=50), nullable=True),
    sa.Column('100', sa.String(length=50), nullable=True),
    sa.Column('200', sa.String(length=50), nullable=True),
    sa.Column('300', sa.String(length=50), nullable=True),
    sa.Column('400', sa.String(length=50), nullable=True),
    sa.Column('500', sa.String(length=50), nullable=True),
    sa.Column('600', sa.String(length=50), nullable=True),
    sa.Column('700', sa.String(length=50), nullable=True),
    sa.Column('800', sa.String(length=50), nullable=True),
    sa.Column('900', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('default', sa.String(length=50), nullable=True),
    sa.Column('paper', sa.String(length=50), nullable=True),
    sa.Column('primary', sa.String(length=50), nullable=True),
    sa.Column('secondary', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_color_id'), 'tipo_color', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('usuario', sa.String(length=255), nullable=True),
    sa.Column('pass', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('borrado', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_tipo_color_id'), table_name='tipo_color')
    op.drop_table('tipo_color')
    op.drop_index(op.f('ix_colores_id'), table_name='colores')
    op.drop_table('colores')
    # ### end Alembic commands ###
